name: backend to Hugging Face Space

on:
  push:
    branches: [main]  # Triggers on any push to main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push backend to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          git init
          git branch -M main
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Sync from GitHub"
          git push --force https://kevansoon:$HF_TOKEN@huggingface.co/spaces/kevansoon/volt-pulse-backend main
